version: "3.3"
services:
  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    ports:
      - "0.0.0.0:8200:8200"
    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    command: ["server"]
    cap_add:
      - IPC_LOCK
    restart: always
